### ISSUE TITLE
imagesearch issue

### ISSUE THREAD

**Issue by 321098123** [AdriaGual/pokemon-pocket-bot#2]
The image search up to the matching process works well, but it doesn’t function properly afterward. In the GIF from the README, it shows the cards on the bench being read, but the cards on my bench are not being recognized. 

I used adb screencap to crop and add the images, but it seems there’s an issue here. In the original source, all card images had the same size of 570x400 and 96 DPI, but the images I captured myself did not. 

Could you please tell me the correct way to capture the card images?

**Comment by AdriaGual** [comment]
Sure! (I feel I should have explained it in the README.md)

So, in order to create new cards, I recommend to change a value on the code:

in the `bot.py` file, there's a method that says:
line 347 - `self.check_cards(False)`

If you change that False to a True, it'll save all the cards that the bot recognizes and store them at the root of the project, if you let it play a bit, it'll capture your image with the correct size and all.

I don't like to use that by default because it generates a lot of images, but maybe it should be easier to trigger.

The other way is using the "Screenshot" option on the app, as the name says, it connects to the emulator and generates a screenshot, then you just have to open that image in 100% resolution and snipe the part you want.

Hope it helps <3

**Comment by 321098123** [comment]
![screenshot](https://github.com/user-attachments/assets/fd99e154-e940-4d04-aead-74c8e3ad766f)

The card image captured by (True)method also didn't work. Like the image above, the card image captured by Dex didn't work either.

language is in english
Captured using adb screencap

**Comment by AdriaGual** [comment]
Ok, I did some updates in order to address this.

If you update the code and the value of the `check_cards` method is True, it will generate a folder called "debug_images" and store them there.

In order to get the charmander image properly cropped, just add that charmander to a deck and start the bot with this deck,

What the function does is to check the cards on the hand and store them properly cutted so they can be recognized, just let the bot play with the charmander deck a bit and then look for the image on the folder I told you before,

Hope it helps!

**Comment by AdriaGual** [comment]
Since I see it can be a bit troublesome to get the images, I did a new feature: `Capture Region`

This feature allows you to take a cropped screenshot, from a position X, Y and a width and height that you need.

It will store the image as `screenshot_region.png`

![image](https://github.com/user-attachments/assets/8c98b7cf-305b-467f-bf7e-20a6e3a24f95)

**Comment by 321098123** [comment]
Thank you i checked the log to see if it recognizes all the hand cards
